spring:
  application:
    name: orm-benchmark-testing
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: rootroot
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  type-aliases-package: com.kotlinorm.mybatisBenchmark.dao
  mapper-locations: "classpath*:/mapper/**/*,Xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
    id-type: auto
    update-strategy: not_null

